SELECT SUPPLIER_CONTACT_INFO.ContactID, SUPPLIER_CONTACT_INFO.ContactTitle, SUPPLIER_CONTACT_INFO.ContactFirstName,
	SUPPLIER_CONTACT_INFO.ContactLastName, SUPPLIER_CONTACT_INFO.ContactEmail, SUPPLIERS.SupplierID, SUPPLIER_INFO.*
FROM SUPPLIER_CONTACT_INFO
INNER JOIN SUPPLIERS ON SUPPLIER_CONTACT_INFO.ContactID = SUPPLIERS.ContactID
INNER JOIN SUPPLIER_INFO ON SUPPLIERS.CompanyName = SUPPLIER_INFO.CompanyName
